-- Crear el usuario VDP correctamente
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token,
  phone_change,
  phone_change_token,
  email_change_token_current,
  recovery_sent_at,
  last_sign_in_at,
  confirmation_sent_at,
  confirmed_at,
  phone_confirmed_at,
  invited_at,
  banned_until,
  deleted_at,
  phone,
  is_anonymous,
  is_super_admin,
  is_sso_user,
  email_change_confirm_status,
  reauthentication_token,
  reauthentication_sent_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  'authenticated',
  'authenticated',
  'vdp@tradsis.net',
  crypt('1234', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{}',
  now(),
  now(),
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  now(),
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  NULL,
  false,
  0,
  NULL,
  NULL
);

-- Crear el perfil correspondiente
INSERT INTO public.profiles (id, first_name, last_name)
VALUES ('f47ac10b-58cc-4372-a567-0e02b2c3d479', 'VDP', 'Admin');