// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqfbldhrdqidpcboyeup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZmJsZGhyZHFpZHBjYm95ZXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTIxNjAsImV4cCI6MjA3MDEyODE2MH0.gPCOWQ2s6vko8vSnepipqavceGLJoluarpjCTiHHfIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});