import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { corsHeaders } from "../_shared/cors.ts";

// ---------- helpers (mirror src/utils/approvedMultiQuantity.ts) ----------
const AUTO_DESCRIPTION_EXCLUDED_LABELS = [
  "tarifa", "forzar máquina", "forzar maquina", "tira y retira",
  "forzar poses", "forzar poses/pags.", "modelos",
];

const normalizePromptKey = (v: any) =>
  String(v ?? "").replace(/\$/g, "").trim().toUpperCase();

const parseQuantity = (v: any): number => {
  if (typeof v === "number") return Number.isFinite(v) && v > 0 ? v : 1;
  const raw = String(v ?? "").trim();
  if (!raw) return 1;
  const norm = raw.includes(",") ? raw.replace(/\./g, "").replace(",", ".") : raw;
  const p = parseFloat(norm);
  return Number.isFinite(p) && p > 0 ? p : 1;
};

const parseLocaleNumber = (v: any): number => {
  if (typeof v === "number") return Number.isFinite(v) ? v : 0;
  const raw = String(v ?? "").trim();
  if (!raw) return 0;
  const norm = raw.includes(",") ? raw.replace(/\./g, "").replace(",", ".") : raw;
  const p = parseFloat(norm);
  return Number.isFinite(p) ? p : 0;
};

const promptsToArray = (prompts: any): any[] => {
  if (Array.isArray(prompts)) {
    return prompts
      .filter((p: any) => p && (p.id || p.name || p.label))
      .map((p: any, i: number) => ({
        ...p,
        id: String(p.id || p.name || p.label || `prompt-${i}`),
        label: p.label || String(p.id || p.name || p.label || `Prompt ${i + 1}`),
        order: p.order ?? i,
      }));
  }
  if (prompts && typeof prompts === "object") {
    return Object.entries(prompts).map(([id, p]: [string, any], i: number) => ({
      id, label: p?.label || id, value: p?.value, order: p?.order ?? i,
    }));
  }
  return [];
};

const findQuantityPromptIndex = (arr: any[]) => {
  const cIdx = arr.findIndex((p) => String(p.id || "").trim() === "custom_quantity");
  if (cIdx >= 0) return cIdx;
  return arr.findIndex((p) => {
    const t = normalizePromptKey(p.label || p.id || "");
    return t.includes("CANTIDAD") || t.includes("UNIDADES") || t.includes("EJEMPLAR")
      || t.includes("QUANTITY") || t === "QTY";
  });
};

const syncPromptsWithQuantity = (
  prompts: any,
  qty: number,
  resolver?: { promptName?: string | null; label?: string | null },
) => {
  const arr = [...promptsToArray(prompts)];
  let idx = -1;

  if (resolver?.promptName || resolver?.label) {
    const normalizedPromptName = resolver.promptName ? normalizePromptKey(resolver.promptName) : "";
    const normalizedLabel = resolver.label ? normalizePromptKey(resolver.label) : "";

    idx = arr.findIndex((p) => {
      const promptId = normalizePromptKey(p?.id || "");
      const promptName = normalizePromptKey(p?.name || "");
      const promptLabel = normalizePromptKey(p?.label || "");

      return (
        (!!normalizedPromptName && (
          promptId === normalizedPromptName ||
          promptName === normalizedPromptName ||
          promptLabel === normalizedPromptName
        )) ||
        (!!normalizedLabel && (
          promptId === normalizedLabel ||
          promptName === normalizedLabel ||
          promptLabel === normalizedLabel
        ))
      );
    });
  }

  if (idx < 0) idx = findQuantityPromptIndex(arr);
  if (idx >= 0) arr[idx] = { ...arr[idx], value: String(qty) };
  return arr;
};

const buildAutoDescriptionFromPrompts = (prompts: any) =>
  promptsToArray(prompts)
    .filter((p) => {
      const v = String(p?.value ?? "").trim();
      const l = String(p?.label ?? "").toLowerCase().trim();
      if (!v || v.toLowerCase() === "no") return false;
      if (AUTO_DESCRIPTION_EXCLUDED_LABELS.some((e) => l.includes(e))) return false;
      return true;
    })
    .map((p) => `${p.label}: ${String(p.value).trim()}`)
    .join("\n");

const looksAutoGeneratedDescription = (description: string | null | undefined) => {
  const lines = String(description ?? "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  const isComponentHeader = (line: string) => /^─+\s*.+\s*─+$/.test(line);
  return lines.length > 0 && lines.every((line) => line.includes(":") || isComponentHeader(line));
};

const applyItemAdditionals = (basePrice: number, item: any, quantity: number): number => {
  const additionals = item?.item_additionals;
  if (!Array.isArray(additionals) || additionals.length === 0) return basePrice;
  const qtyInputs: number[] = item?.multi?.qtyInputs || [];
  const qtyIndex = qtyInputs.findIndex((q: number) => Number(q) === Number(quantity));
  let total = basePrice;
  for (const a of additionals) {
    let value = a.value || 0;
    if (a.type === "net_amount" && Array.isArray(a.multiValues)
        && qtyIndex >= 0 && qtyIndex < a.multiValues.length) {
      value = Number(a.multiValues[qtyIndex]) || value;
    }
    const isDiscount = a.is_discount === true || value < 0;
    if (isDiscount) {
      if (a.type === "net_amount") total -= Math.abs(value);
      else if (a.type === "percentage") total -= Math.abs((total * value) / 100);
      continue;
    }
    switch (a.type) {
      case "net_amount": total += value; break;
      case "percentage": total += (total * value) / 100; break;
      case "quantity_multiplier": total += value * quantity; break;
      case "capacity_divider": {
        const cap = a.capacity_value || 1;
        total += value * Math.ceil(quantity / cap);
        break;
      }
    }
  }
  return total;
};

const isCustomProductItem = (item: any) =>
  String(item?.product_id ?? "").trim() === "__CUSTOM_PRODUCT__";

const isQuantityPromptText = (text: string) => {
  const t = normalizePromptKey(text);
  return t.includes("CANTIDAD") || t.includes("UNIDADES") || t.includes("EJEMPLAR")
    || t.includes("QUANTITY") || t === "QTY";
};

const syncCompositeDataWithQuantity = (compositeData: any, quantity: number): any => {
  if (!compositeData || typeof compositeData !== "object") return compositeData;
  const components = compositeData.components;
  if (!components || typeof components !== "object") return compositeData;
  const newComponents: any = Array.isArray(components) ? [...components] : { ...components };
  for (const compId of Object.keys(newComponents)) {
    const compEntry = newComponents[compId];
    if (!compEntry || typeof compEntry !== "object") continue;
    const instances: any = { ...compEntry };
    for (const idx of Object.keys(instances)) {
      const inst = instances[idx];
      if (inst && typeof inst === "object" && Array.isArray((inst as any).prompts)) {
        const newPrompts = (inst as any).prompts.map((p: any) => {
          if (!p || typeof p !== "object") return p;
          const text = p.promptText || p.label || p.name || p.id || "";
          if (isQuantityPromptText(String(text))) {
            const next = { ...p };
            if ("currentValue" in p) next.currentValue = String(quantity);
            if ("value" in p) next.value = String(quantity);
            if (!("currentValue" in p) && !("value" in p)) next.currentValue = String(quantity);
            return next;
          }
          return p;
        });
        instances[idx] = { ...(inst as any), prompts: newPrompts };
      }
    }
    newComponents[compId] = instances;
  }
  return { ...compositeData, components: newComponents };
};

const getYearString = (year: number, format: string) =>
  format === "YYYY" ? String(year) : String(year % 100).padStart(2, "0");

const getNextOrderNumberFallback = async (supabase: any, organizationId: string) => {
  const currentYear = new Date().getUTCFullYear();

  const { data: formatRow } = await supabase
    .from("numbering_formats")
    .select("prefix, suffix, use_year, year_format, sequential_digits")
    .eq("organization_id", organizationId)
    .eq("document_type", "order")
    .maybeSingle();

  const prefix = formatRow?.prefix ?? "SO-";
  const suffix = formatRow?.suffix ?? "";
  const useYear = formatRow?.use_year ?? true;
  const yearFormat = formatRow?.year_format ?? "YYYY";
  const digits = formatRow?.sequential_digits ?? 4;
  const yearBucket = useYear ? currentYear : 0;

  let ordersQuery = supabase
    .from("sales_orders")
    .select("order_number, created_at")
    .eq("organization_id", organizationId)
    .not("order_number", "is", null);

  if (useYear) {
    ordersQuery = ordersQuery
      .gte("created_at", `${currentYear}-01-01T00:00:00.000Z`)
      .lt("created_at", `${currentYear + 1}-01-01T00:00:00.000Z`);
  }

  const [{ data: existingOrders }, { data: sequenceRow }] = await Promise.all([
    ordersQuery,
    supabase
      .from("document_sequences")
      .select("last_number")
      .eq("organization_id", organizationId)
      .eq("document_type", "order")
      .eq("year", yearBucket)
      .maybeSingle(),
  ]);

  const existingMax = Math.max(
    0,
    ...(existingOrders || []).map((order: any) => {
      const match = String(order?.order_number ?? "").match(/(\d+)$/);
      return match ? Number(match[1]) || 0 : 0;
    }),
  );

  const nextSequential = Math.max((sequenceRow?.last_number ?? 0) + 1, existingMax + 1, 1);
  const yearString = useYear ? `${getYearString(currentYear, yearFormat)}-` : "";
  const orderNumber = `${prefix}${yearString}${String(nextSequential).padStart(digits, "0")}${suffix}`;

  await supabase.from("document_sequences").upsert({
    organization_id: organizationId,
    document_type: "order",
    year: yearBucket,
    last_number: nextSequential,
    updated_at: new Date().toISOString(),
  });

  return orderNumber;
};

const getBearerToken = (authHeader: string | null) =>
  authHeader?.replace(/^Bearer\s+/i, "").trim() || null;

const validatePortalTokenForQuote = async (supabase: any, portalToken: string, quoteId: string) => {
  const { data: tokenData, error: tokenError } = await supabase
    .from("quote_portal_tokens")
    .select("id, quote_id, is_active, expires_at")
    .eq("token", portalToken)
    .maybeSingle();

  if (tokenError || !tokenData) {
    throw new Error("Token de portal inválido o expirado");
  }

  if (tokenData.quote_id !== quoteId) {
    throw new Error("El token de portal no corresponde a este presupuesto");
  }

  if (new Date(tokenData.expires_at) < new Date()) {
    throw new Error("Este enlace ha expirado");
  }

  if (!tokenData.is_active) {
    throw new Error("Este presupuesto ya ha sido respondido");
  }

  return tokenData;
};

// ---------- main approval logic (port of useQuoteApproval) ----------
async function approveQuoteCore(
  supabase: any,
  params: {
    quoteId: string;
    selectedItemIds?: string[];
    itemQuantities?: Record<string, number>;
    actorUserId?: string | null;
    actorAuthHeader?: string | null;
    portalToken?: string | null;
  },
) {
  const { quoteId, selectedItemIds, itemQuantities, actorUserId, actorAuthHeader, portalToken } = params;

  const { data: quote, error: quoteError } = await supabase
    .from("quotes")
    .select("*, items:quote_items(*)")
    .eq("id", quoteId)
    .single();
  if (quoteError) throw quoteError;
  if (!quote) throw new Error("Presupuesto no encontrado");

  const isPortalApproval = !!portalToken;
  if (isPortalApproval) {
    await validatePortalTokenForQuote(supabase, portalToken, quoteId);
  } else {
    if (!actorUserId) throw new Error("Unauthorized");

    const isOwnQuote = quote.user_id === actorUserId;
    const organizationId = quote.organization_id;

    const [{ data: membership }, { data: ownedOrg }] = await Promise.all([
      organizationId
        ? supabase
            .from("organization_members")
            .select("role")
            .eq("organization_id", organizationId)
            .eq("user_id", actorUserId)
            .maybeSingle()
        : Promise.resolve({ data: null }),
      organizationId
        ? supabase
            .from("organizations")
            .select("id")
            .eq("id", organizationId)
            .eq("api_user_id", actorUserId)
            .maybeSingle()
        : Promise.resolve({ data: null }),
    ]);

    const role = String(membership?.role || "").toLowerCase();
    const canApprove = !!ownedOrg || role === "admin" || role === "gestor" || (role === "comercial" && isOwnQuote);

    if (!canApprove) {
      throw new Error("No tienes permiso para aprobar este presupuesto");
    }
  }

  // Block duplicate
  const { data: existingOrder } = await supabase
    .from("sales_orders")
    .select("id, order_number")
    .eq("quote_id", quoteId)
    .maybeSingle();
  if (existingOrder) {
    throw new Error(`Este presupuesto ya tiene un pedido asociado (${existingOrder.order_number}).`);
  }

  const itemsToApprove = selectedItemIds && selectedItemIds.length > 0
    ? quote.items.filter((it: any) => selectedItemIds.includes(it.id))
    : quote.items;
  if (!itemsToApprove?.length) throw new Error("No hay items para aprobar");

  // Ensure every multi-qty item has a quantity; prioritize the stored/sent quantity
  // and only fall back to the first row when there is truly no persisted quantity.
  const resolvedQuantities: Record<string, number> = { ...(itemQuantities || {}) };
  for (const it of itemsToApprove) {
    const m = it.multi as any;
    if (m?.rows && Array.isArray(m.rows) && m.rows.length > 1) {
      const provided = Number(resolvedQuantities[it.id]);
      if (!Number.isFinite(provided) || provided <= 0) {
        const storedQty = it.accepted_quantity
          ? parseQuantity(it.accepted_quantity)
          : it.quantity
            ? parseQuantity(it.quantity)
            : null;
        if (storedQty && Number.isFinite(storedQty) && storedQty > 0) {
          resolvedQuantities[it.id] = storedQty;
        } else {
          const firstQty = Number(m.rows[0]?.qty ?? m.rows[0]?.quantity);
          if (Number.isFinite(firstQty) && firstQty > 0) {
            resolvedQuantities[it.id] = firstQty;
          } else {
            throw new Error("Debes seleccionar una cantidad para cada item con múltiples opciones");
          }
        }
      }
    }
  }

  const organizationId = quote.organization_id;
  if (!organizationId) throw new Error("No se pudo determinar la organización");

  // Order number with retry. Public portal approvals may not have auth.uid(),
  // so fall back to service-role sequence generation if the RPC denies access.
  let orderNumber = "";
  for (let i = 0; i < 3; i++) {
    const { data: docNumber, error: docErr } = await supabase
      .rpc("next_document_number", { p_organization_id: organizationId, p_document_type: "order" });

    if (docErr || !docNumber?.length) {
      console.warn("next_document_number failed in approve-quote, using fallback:", docErr?.message || "sin resultado");
      orderNumber = await getNextOrderNumberFallback(supabase, organizationId);
    } else {
      orderNumber = docNumber[0].document_number;
    }

    const { data: ex } = await supabase
      .from("sales_orders")
      .select("id")
      .eq("organization_id", organizationId)
      .eq("order_number", orderNumber)
      .maybeSingle();
    if (!ex) break;
    if (i === 2) throw new Error("No se pudo generar un número de pedido único");
  }

  // Quantity prompt resolution from settings
  const quantityPromptByProduct = new Map<string, { promptName: string; label: string | null }>();
  const productIds = Array.from(new Set(
    itemsToApprove.map((it: any) => String(it.product_id ?? "").trim()).filter(Boolean)
  ));
  if (productIds.length > 0) {
    const { data: qs } = await supabase
      .from("product_prompt_settings")
      .select("easyquote_product_id, prompt_name, label")
      .eq("organization_id", organizationId)
      .eq("is_quantity", true)
      .in("easyquote_product_id", productIds);
    for (const r of qs || []) {
      if (!quantityPromptByProduct.has(r.easyquote_product_id)) {
        quantityPromptByProduct.set(r.easyquote_product_id, { promptName: r.prompt_name, label: r.label });
      }
    }
  }

  const resolveQtyStrict = (item: any): number | null => {
    const arr = promptsToArray(item.prompts);
    const setting = item.product_id ? quantityPromptByProduct.get(String(item.product_id)) : undefined;
    if (setting) {
      const nName = normalizePromptKey(setting.promptName);
      const nLabel = setting.label ? normalizePromptKey(setting.label) : "";
      const idx = arr.findIndex((p: any) => {
        const pn = normalizePromptKey(p?.name || p?.id || "");
        const pl = normalizePromptKey(p?.label || "");
        return pn === nName || pl === nName || (nLabel && (pn === nLabel || pl === nLabel));
      });
      if (idx >= 0) {
        const q = parseQuantity(arr[idx]?.value);
        if (q > 0) return q;
      }
    }
    const idx2 = findQuantityPromptIndex(arr);
    if (idx2 >= 0) {
      const q = parseQuantity(arr[idx2]?.value);
      if (q > 0) return q;
    }
    if (item.accepted_quantity) return parseQuantity(item.accepted_quantity);
    if (item.quantity) return parseQuantity(item.quantity);
    return null;
  };

  const resolveQty = (item: any): number => {
    const s = resolveQtyStrict(item);
    if (s !== null) return s;
    if (isCustomProductItem(item)) return 1;
    throw new Error(`No se pudo resolver la cantidad del item ${item.product_name || item.id}`);
  };

  const customBasePrice = (item: any, quantity: number): number => {
    const arr = promptsToArray(item.prompts);
    const cp = arr.find((p: any) => String(p?.id || p?.name || "").trim() === "custom_unit_price");
    const unit = parseLocaleNumber(cp?.value);
    const sQty = resolveQtyStrict(item);
    if (unit > 0 && sQty !== null && sQty > 0) return unit * sQty;
    return parseLocaleNumber(item.price || 0);
  };

  const approvalMatchesStoredQuote =
    itemsToApprove.length === quote.items.length
    && itemsToApprove.every((item: any) => {
      const storedQty = resolveQty(item);
      const selectedQty = Number(resolvedQuantities[item.id] ?? storedQty);
      return Number.isFinite(selectedQty) && selectedQty === storedQty;
    });

  // Subtotal
  let subtotal = 0;
  for (const item of itemsToApprove) {
    const m = item.multi as any;
    const rq = resolveQty(item);
    let price = isCustomProductItem(item)
      ? applyItemAdditionals(customBasePrice(item, rq), item, rq)
      : parseLocaleNumber(item.price || 0);
    // Solo recalcular si el usuario seleccionó una cantidad DISTINTA a la guardada
    if (m?.rows?.length && resolvedQuantities[item.id]) {
      const sQ = resolvedQuantities[item.id];
      const storedQ = parseQuantity(item.quantity ?? item.accepted_quantity ?? rq);
      if (sQ !== storedQ) {
        const row = m.rows.find((r: any) => parseQuantity(r.qty) === sQ || parseQuantity(r.quantity) === sQ);
        if (row) {
          const base = parseFloat(row.outs?.find((o: any) => o.type === "Price")?.value || row.price || item.price || 0);
          price = applyItemAdditionals(base, item, sQ);
        }
      }
    }
    subtotal += price;
  }

  // Additionals
  const { data: quoteAdditionals } = await supabase
    .from("quote_additionals").select("*").eq("quote_id", quoteId);
  let discountAmount = 0, taxAmount = 0;
  for (const a of quoteAdditionals || []) {
    if (a.is_discount) {
      discountAmount += a.type === "percentage" ? (subtotal * a.value) / 100 : a.value;
    } else {
      taxAmount += a.type === "percentage" ? (subtotal * a.value) / 100 : a.value;
    }
  }
  const finalPrice = subtotal - discountAmount + taxAmount;

  const persistedSubtotal = parseLocaleNumber(quote.subtotal || 0);
  const persistedDiscount = parseLocaleNumber(quote.discount_amount || 0);
  const persistedTax = parseLocaleNumber(quote.tax_amount || 0);
  const persistedFinalPrice = parseLocaleNumber(quote.final_price || 0);

  const orderSubtotal = approvalMatchesStoredQuote ? persistedSubtotal : subtotal;
  const orderDiscountAmount = approvalMatchesStoredQuote ? persistedDiscount : discountAmount;
  const orderTaxAmount = approvalMatchesStoredQuote ? persistedTax : taxAmount;
  const orderFinalPrice = approvalMatchesStoredQuote ? persistedFinalPrice : finalPrice;

  // Compute delivery_date from organization's default business days (skip weekends)
  let computedDeliveryDate: string | null = null;
  try {
    const { data: orgRow } = await supabase
      .from("organizations")
      .select("default_delivery_business_days")
      .eq("id", quote.organization_id)
      .maybeSingle();
    const days = Number(orgRow?.default_delivery_business_days || 0);
    if (days > 0) {
      const d = new Date();
      let added = 0;
      while (added < days) {
        d.setDate(d.getDate() + 1);
        const day = d.getDay();
        if (day !== 0 && day !== 6) added++;
      }
      computedDeliveryDate = d.toISOString().slice(0, 10);
    }
  } catch (e) {
    console.warn("Could not compute delivery_date:", e);
  }

  // Create order
  const { data: salesOrder, error: orderError } = await supabase
    .from("sales_orders")
    .insert({
      order_number: orderNumber,
      quote_id: quoteId,
      customer_id: quote.customer_id,
      user_id: quote.user_id,
      organization_id: quote.organization_id,
      status: "pending",
      description: quote.description,
      terms_conditions: quote.terms_conditions,
      valid_until: quote.valid_until,
      delivery_date: computedDeliveryDate,
      subtotal: orderSubtotal,
      tax_amount: orderTaxAmount,
      discount_amount: orderDiscountAmount,
      final_price: orderFinalPrice,
      notes: quote.notes,
      created_from_scratch: false,
    })
    .select()
    .single();
  if (orderError) throw orderError;

  if (quoteAdditionals?.length) {
    await supabase.from("sales_order_additionals").insert(
      quoteAdditionals.map((qa: any) => ({
        sales_order_id: salesOrder.id,
        additional_id: qa.additional_id,
        name: qa.name, type: qa.type, value: qa.value, is_discount: qa.is_discount,
      }))
    );
  }

  // Build order items
  const orderItems = itemsToApprove.map((item: any, index: number) => {
    const m = item.multi as any;
    let finalQuantity = resolveQty(item);
    if (m?.rows?.length > 1 && resolvedQuantities[item.id]) finalQuantity = resolvedQuantities[item.id];

    const isCustom = isCustomProductItem(item);
    let fPrice = parseLocaleNumber(item.price || 0);
    let fMulti = item.multi;
    let fOutputs = Array.isArray(item.outputs) ? item.outputs : [];
    const quantityResolver = item.product_id
      ? quantityPromptByProduct.get(String(item.product_id))
      : undefined;
    let fPrompts = syncPromptsWithQuantity(item.prompts, finalQuantity, quantityResolver);
    const baseAutoDesc = buildAutoDescriptionFromPrompts(item.prompts);
    const trimmedDescription = item.description?.trim() || "";
    const hasManualDescription = item.description_manual === true
      || (!!trimmedDescription
        && trimmedDescription !== (item.product_name || item.name || "").trim()
        && trimmedDescription !== (baseAutoDesc || "").trim()
        && !looksAutoGeneratedDescription(trimmedDescription));
    let fDesc = item.description;

    if (isCustom) {
      fPrice = applyItemAdditionals(customBasePrice(item, finalQuantity), item, finalQuantity);
    }

    if (m?.rows?.length > 1 && resolvedQuantities[item.id]) {
      const sQ = resolvedQuantities[item.id];
      const storedQ = parseQuantity(item.quantity ?? item.accepted_quantity ?? finalQuantity);
      const row = m.rows.find((r: any) => parseQuantity(r.qty) === sQ || parseQuantity(r.quantity) === sQ);
      fPrompts = syncPromptsWithQuantity(item.prompts, sQ, quantityResolver);
      if (row) {
        fOutputs = Array.isArray(row.outs) ? row.outs : fOutputs;
        fMulti = { ...m, rows: [row] };
        // Solo recalcular precio si la cantidad seleccionada difiere de la guardada
        if (sQ !== storedQ && !isCustom) {
          const base = parseFloat(row.outs?.find((o: any) => o.type === "Price")?.value || row.price || item.price || 0);
          fPrice = applyItemAdditionals(base, item, sQ);
        }
      }
    }

    if (m?.rows?.length === 1 && !isCustom) {
      const row = m.rows[0];
      fOutputs = Array.isArray(row.outs) ? row.outs : fOutputs;
      // Mantener el precio guardado; NO recalcular desde row.outs + additionals
    }

    if (isCustom) fDesc = item.description || fDesc || "";
    else if (hasManualDescription && fDesc?.trim()) { /* keep */ }
    else fDesc = buildAutoDescriptionFromPrompts(fPrompts) || fDesc || "";

    return {
      sales_order_id: salesOrder.id,
      product_id: item.product_id,
      product_name: item.name || item.product_name,
      description: fDesc,
      description_manual: isCustom ? true : hasManualDescription,
      quantity: finalQuantity,
      price: fPrice,
      outputs: fOutputs,
      prompts: fPrompts,
      multi: fMulti,
      position: index,
      composite_data: item.composite_data
        ? syncCompositeDataWithQuantity(item.composite_data, finalQuantity)
        : null,
      item_additionals: item.item_additionals || null,
    };
  });

  const { error: itemsError } = await supabase.from("sales_order_items").insert(orderItems);
  if (itemsError) {
    await supabase.from("sales_orders").delete().eq("id", salesOrder.id);
    throw itemsError;
  }

  // Copy attachments
  try {
    const { data: atts } = await supabase
      .from("document_attachments")
      .select("*")
      .eq("quote_id", quoteId);
    if (atts?.length) {
      await supabase.from("document_attachments").insert(
        atts.map((a: any) => ({
          organization_id: a.organization_id,
          sales_order_id: salesOrder.id,
          file_name: a.file_name, file_path: a.file_path,
          file_size: a.file_size, mime_type: a.mime_type,
          created_by: a.created_by,
        }))
      );
    }
  } catch (e) { console.error("attachments copy failed (non-fatal):", e); }

  // Mark accepted/non-accepted
  const allItemIds = quote.items.map((it: any) => it.id);
  const approvedIds = itemsToApprove.map((it: any) => it.id);
  const nonApprovedIds = allItemIds.filter((id: string) => !approvedIds.includes(id));

  for (let i = 0; i < orderItems.length; i++) {
    const oi = orderItems[i];
    const src = itemsToApprove[i];
    await supabase.from("quote_items").update({
      accepted: true,
      accepted_quantity: oi.quantity,
      quantity: oi.quantity,
      price: oi.price,
      prompts: oi.prompts,
      outputs: oi.outputs,
      multi: oi.multi,
      description: oi.description,
    }).eq("id", src.id);
  }
  if (nonApprovedIds.length) {
    await supabase.from("quote_items").update({ accepted: false }).in("id", nonApprovedIds);
  }

  // Update quote totals + status
  const updatedSelections = Array.isArray(quote.selections)
    ? quote.selections.map((sel: any) => {
        const match = orderItems.find((oi: any) => {
          const sp = String(sel?.productId ?? "").trim();
          const sn = String(sel?.displayName || sel?.productName || sel?.itemDescription || "").trim();
          return (sp && sp === String(oi.product_id ?? "").trim()) || sn === String(oi.product_name || "").trim();
        });
        if (!match) return sel;
        return {
          ...sel, price: match.price, outputs: match.outputs, prompts: match.prompts,
          multi: match.multi, itemDescription: match.description, descriptionManual: match.description_manual,
        };
      })
    : quote.selections;

  await supabase.from("quotes").update({
    status: "approved",
    subtotal: orderSubtotal,
    tax_amount: orderTaxAmount,
    discount_amount: orderDiscountAmount,
    final_price: orderFinalPrice,
    selections: updatedSelections,
  }).eq("id", quoteId);

  // Holded exports — best effort
  try {
    const { data: holdedIntegration } = await supabase
      .from("integrations")
      .select("id")
      .eq("name", "Holded")
      .maybeSingle();
    let active = false;
    let mode: string = "all";
    if (holdedIntegration?.id) {
      const { data: access } = await supabase
        .from("organization_integration_access")
        .select("is_active, access_token_encrypted, configuration")
        .eq("organization_id", organizationId)
        .eq("integration_id", holdedIntegration.id)
        .maybeSingle();
      active = !!(access?.is_active && access?.access_token_encrypted);
      mode = (access?.configuration as any)?.export_mode || "all";
    }
    // The downstream Holded exporters require a USER auth header (they use
    // supabase.auth.getUser to validate access). When approve-quote is called
    // from the app, we must forward the caller's Authorization header so the
    // invoke is treated as an authenticated request — otherwise both exports
    // silently 401 and the Holded sync never happens.
    const invokeHeaders: Record<string, string> = {};
    if (actorAuthHeader) invokeHeaders.Authorization = actorAuthHeader;
    if (portalToken) invokeHeaders["x-portal-token"] = portalToken;
    const invokeOpts = (body: any) => ({
      body,
      headers: Object.keys(invokeHeaders).length > 0 ? invokeHeaders : undefined,
    });
    if (active && (mode === "estimates_on_approval")) {
      const { error: estErr } = await supabase.functions.invoke(
        "holded-export-estimate",
        invokeOpts({ quoteId, approvedItemIds: approvedIds }),
      );
      if (estErr) console.error("Holded estimate export failed:", estErr);
      else console.log("Holded estimate export OK for quote", quoteId);
    }
    if (active && (mode === "all" || mode === "orders_only" || mode === "estimates_on_approval")) {
      const { error: ordErr } = await supabase.functions.invoke(
        "holded-export-order",
        invokeOpts({ orderId: salesOrder.id }),
      );
      if (ordErr) console.error("Holded order export failed:", ordErr);
      else console.log("Holded order export OK for order", salesOrder.id);
    }
  } catch (e) { console.error("Holded export failed (non-fatal):", e); }

  return { salesOrder, orderNumber };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  try {
    const body = await req.json();
    const { quoteId, selectedItemIds, itemQuantities } = body || {};
    if (!quoteId) {
      return new Response(JSON.stringify({ error: "quoteId requerido" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }
    const actorAuthHeader = req.headers.get("authorization");
    const portalToken = req.headers.get("x-portal-token");
    const bearerToken = getBearerToken(actorAuthHeader);
    let actorUserId: string | null = null;

    if (bearerToken) {
      const { data: { user }, error: authError } = await supabase.auth.getUser(bearerToken);
      if (authError || !user) {
        return new Response(JSON.stringify({ error: "Unauthorized" }), {
          status: 401,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      actorUserId = user.id;
    }

    if (!actorUserId && !portalToken) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const result = await approveQuoteCore(supabase, {
      quoteId, selectedItemIds, itemQuantities, actorUserId, actorAuthHeader, portalToken,
    });
    return new Response(JSON.stringify({ success: true, ...result }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e: any) {
    console.error("approve-quote error:", e);
    return new Response(JSON.stringify({ error: e.message || "Error interno" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});